services:

  db:
    container_name: teste_guia_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql/:/docker-entrypoint-initdb.d/
  api:
    container_name: teste_guia_api
    build: ./api  # FIXED: Use `build` instead of `image`
    restart: always
    depends_on:
      - db  # Ensures `db` starts first
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CRONTAB: ${CRONTAB}
    ports:
      - 8000:8000
  dashboard:
    container_name: teste_guia_dashboard
    build: ./dashboard
    depends_on:
      - api
    environment:
      - BACKEND_URL=http://api:8000/api/v1
      - CACHE_VALID_DURATION=600
    ports:
      - 8501:8501
volumes:
  postgres: