services:

  db:
    container_name: teste_guia_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql/:/docker-entrypoint-initdb.d/
  api:
    container_name: teste_guia_api
  dashboard:
    container_name: teste_guia_dashboard
    image: imageName

volumes:
  postgres: